app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('apps.index.urls')),
                  path('account/', include('apps.account.urls')),
                  path('group/', include('apps.group.urls')),
                  path('post/', include('apps.post.urls')),
                  path('technology/', include('apps.technology.urls')),
                  path('announcements/', include('apps.announcements.urls')),
                  path('user/', include('apps.user.urls')),
                  path('autocomplete/', include('apps.autocomplete.urls')),
                  path('attachment/', include('apps.attachment.urls')),
                  path('admin/', admin.site.urls),
                  path('tinymce/', include('tinymce.urls')),
                  path('meet/', include('apps.meets_calendar.urls')),
                  path('git/', include('apps.git_service.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

app/apps/announcements/urls.py
from django.urls import path

from . import views

app_name = 'announcement'
urlpatterns = [
    path('', views.AnnouncementListView.as_view(), name='announcement-list'),
    # path('my-groups/', views.UserGroupsListView.as_view(), name='user-group-list'),
    # path('<int:pk>', views.GroupDetailView.as_view(), name='group-detail'),
    path('new/', views.AnnouncementCreateView.as_view(), name='announcement-create'),
]

app/apps/attachment/urls.py
from django.urls import path

from . import views

app_name = 'attachment'
urlpatterns = [
    path('<int:pk>/new', views.CreateAttachmentView.as_view(), name='create-attachment')
]

app/apps/group/urls.py
from django.urls import path

from . import views

app_name = 'group'
urlpatterns = [
    path('', views.GroupListView.as_view(), {'title': 'testTitle'}, name='group-list'),
    path('my-groups/', views.UserGroupsListView.as_view(), {'title': 'testTitle'}, name='user-group-list'),
    path('<int:pk>', views.GroupDetailView.as_view(), name='group-detail'),
    path('new/', views.GroupCreateView.as_view(), name='group-create'),
    path('<int:pk>/update', views.GroupUpdateView.as_view(), name='group-update'),
    path('<int:pk>/site/private/', views.PrivateGroupSiteDetailView.as_view(), name='private-group-site-detail'),
    path('<int:pk>/site/public/', views.PublicGroupSiteDetailView.as_view(), name='public-group-site-detail'),
    path('<int:pk>/site/update/<int:is_public>', views.GroupSiteUpdateView.as_view(), name='group-site-update'),
    path('<int:pk>/members', views.GroupMembersView.as_view(), name='group-members'),
    path('<int:pk>/accept', views.GroupAcceptMembershipView.as_view(), name='group-accept-membership'),
    path('<int:groupid>/members/update/<int:userid>/<int:action>', views.GroupMembersManagementView.as_view(), name='group-management'),
    path('<int:pk>/members/add', views.AddMemberToGroupView.as_view(), name='add-group-user'),
    path('<int:pk>/integrations', views.GroupIntegrations.as_view(), name='group-integrations')
]

app/apps/user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('supervisors/', views.SupervisorsListView.as_view(), name='supervisor-list'),
]

app/apps/index/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pja Diploma</title>
    <meta name="referrer" content="strict-origin"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/main.css' %}">
</head>
<body>
{#  =======  #}
{#  CONTENT  #}
{#  =======  #}
{% include 'base/header.html' %}
{% include 'base/sidebar.html' %}
<main id="main" class="main">
    <section class="section">
        {% block content %}
            {% endblock %}
    </section>
</main>

{#  =======  #}
{#  PAGE_END  #}
{#  =======  #}
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'assets/vendor/jquery/jquery.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.js' %}"></script>
<script src="{% static 'assets/vendor/moment/moment.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
<script>
    function openModal(ev) {
      ev.preventDefault();

      console.log(ev.target.href);

      $.ajax({
          url: ev.target.href,
          type: "GET",
          data: {},
          async: true,
          success: function (result) {
              $('#baseModal').html(result);
          }
      });

      $('#baseModal').toggle();
    }

    function closeModal() {
        $('#baseModal').hide();
    }
</script>
<div id="baseModal" class="modal modal-backdrop" role="dialog"></div>
{% block footer %}
{% endblock %}
</body>
</html>

app/apps/index/templates/base/card.html
{% load static %}
<div class="card">
    <div class="card-header">
        <div>
            {% block header %}
            {% endblock %}
        </div>
    </div>
    <div class="card-body">
        <div>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>

app/apps/index/templates/base/header.html
{% load static %}
{% load notifications %}
<header class="header fixed-top d-flex align-items-center">
    <div class="d-flex align-items-center justify-content-between">
        <a href="{% url 'index' %}" class="logo d-flex align-items-center">
            <img class="logo-img" src="{% static "base/img/Logo_PL_2.png" %}" alt="PJA Logo">
        </a>
        <i class="bi bi-list toggle-sidebar-btn">
        </i>
    </div>
    <nav class="header-nav ms-auto">
        {% if user.is_authenticated %}
            <ul class="d-flex align-items-center">
                {% notifications user %}
                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        <img src="{{ user.get_avatar_url }}" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">{{ user.username }}</span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile" style="">
                        <li class="dropdown-header">
                            <h6>{{ user.first_name }} {{ user.last_name }}</h6>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'user-update' %}">
                                <i class="bi bi-person"></i>
                                <span>Profil</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Wyloguj się</span>
                            </a>
                        </li>

                    </ul>
                </li>
            </ul>
        {% endif %}
    </nav>
</header>

app/apps/index/templates/base/sidebar.html
{% load static %}
{% load user_role_tags %}
<aside id="sidebar" class="sidebar">
    {% with request.resolver_match.url_name as app_name %}
        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'group:user-group-list' %}">
                    <i class="bi bi-people"></i>
                    <span>Moje Grupy</span>
                </a>
                {% if app_name in 'group-detail,group-update,private-group-site-detail,public-group-site-detail,group-site-update,group-members,create-attachment,group-integrations' %}
                    <ul class="nav-content collapse show">
                        {% if role != null %}
                            <a href="{% url 'group:group-detail' group.id %}">
                                <i class="bi bi-circle"></i>
                                <span>Grupa</span>
                            </a>
                            <a href="{% url 'group:public-group-site-detail' group.id %}">
                                <i class="bi bi-circle"></i>
                                <span>Strona Publiczna</span>
                            </a>
                            <a href="{% url 'group:private-group-site-detail' group.id %}">
                                <i class="bi bi-circle"></i>
                                <span>Strona Prywatna</span>
                            </a>
                            <a href="{% url 'attachment:create-attachment' group.id %}">
                                <i class="bi bi-circle"></i>
                                <span>Dodaj Dokument</span>
                            </a>
                            {% if role == 1 or role == 2 %}
                                <a href="{% url 'group:group-update' group.id %}">
                                    <i class="bi bi-circle"></i>
                                    <span>Ustawienia Grupy</span>
                                </a>
                            {% endif %}
                            <a href="{% url 'group:group-integrations' group.id %}">
                                <i class="bi bi-circle"></i>
                                <span>Integracje</span>
                            </a>
                        {% endif %}
                        {% if user.is_supervisor %}
                            <a href="{% url 'group:group-members' group.id %}">
                                <i class="bi bi-circle"></i>
                                <span>Zarządzaj Członkami</span>
                            </a>
                            <a href="{% url 'meet:new-meet' group.id %}" onclick="openModal(event)">
                                <i class="bi bi-circle"></i>
                                <span>Dodaj Spotkanie</span>
                            </a>

                        {% endif %}
                    </ul>
                {% endif %}
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'group:group-list' %}">
                    <i class="bi bi-grid"></i>
                    <span>Grupy</span>
                </a>
            </li>


            {% if user.is_supervisor %}
                <li class="nav-item">
                    <a class="nav-link collapsed" href="{% url 'group:group-create' %}">
                        <i class="bi bi-plus-circle-fill"></i>
                        <span>STWÓRZ GRUPĘ</span>
                    </a>
                </li>
            {% endif %}

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'announcement:announcement-list' %}">
                    <i class="bi bi-volume-up-fill"></i>
                    <span>OGŁOSZENIA</span>
                </a>
                {% if app_name in 'announcement-list,announcement-create' %}
                    {% if user.is_supervisor %}
                        <ul class="nav-content collapse show">
                            <a href="{% url 'announcement:announcement-create' %}">
                                <i class="bi bi-circle"></i>
                                <span>Dodaj ogłoszenie</span>
                            </a>
                        </ul>
                    {% endif %}
                {% endif %}
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'user:supervisor-list' %}">
                    <i class="bi bi-file-earmark-person"></i>
                    <span>Dydaktycy</span>
                </a>
            </li>

        </ul>
    {% endwith %}
</aside>