app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('apps.index.urls')),
                  path('account/', include('apps.account.urls')),
                  path('group/', include('apps.group.urls')),
                  path('post/', include('apps.post.urls')),
                  path('technology/', include('apps.technology.urls')),
                  path('announcements/', include('apps.announcements.urls')),
                  path('user/', include('apps.user.urls')),
                  path('autocomplete/', include('apps.autocomplete.urls')),
                  path('attachment/', include('apps.attachment.urls')),
                  path('admin/', admin.site.urls),
                  path('tinymce/', include('tinymce.urls')),
                  path('meet/', include('apps.meets_calendar.urls')),
                  path('git/', include('apps.git_service.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

app/apps/group/urls.py
from django.urls import path

from . import views

app_name = 'group'
urlpatterns = [
    path('', views.GroupListView.as_view(), {'title': 'testTitle'}, name='group-list'),
    path('my-groups/', views.UserGroupsListView.as_view(), {'title': 'testTitle'}, name='user-group-list'),
    path('<int:pk>', views.GroupDetailView.as_view(), name='group-detail'),
    path('new/', views.GroupCreateView.as_view(), name='group-create'),
    path('<int:pk>/update', views.GroupUpdateView.as_view(), name='group-update'),
    path('<int:pk>/site/private/', views.PrivateGroupSiteDetailView.as_view(), name='private-group-site-detail'),
    path('<int:pk>/site/public/', views.PublicGroupSiteDetailView.as_view(), name='public-group-site-detail'),
    path('<int:pk>/site/update/<int:is_public>', views.GroupSiteUpdateView.as_view(), name='group-site-update'),
    path('<int:pk>/members', views.GroupMembersView.as_view(), name='group-members'),
    path('<int:pk>/accept', views.GroupAcceptMembershipView.as_view(), name='group-accept-membership'),
    path('<int:groupid>/members/update/<int:userid>/<int:action>', views.GroupMembersManagementView.as_view(), name='group-management'),
    path('<int:pk>/members/add', views.AddMemberToGroupView.as_view(), name='add-group-user'),
    path('<int:pk>/integrations', views.GroupIntegrations.as_view(), name='group-integrations')
]

app/apps/group/forms.py
from bootstrap_datepicker_plus import DatePickerInput
from dal import autocomplete, forward
from dal_select2_tagging.widgets import TaggingSelect2
from django import forms
from tinymce.widgets import TinyMCE

from apps.account import models as user_models
from utils.forms import fields
from . import models


class GroupForm(forms.ModelForm):
    team_leader = forms.ModelChoiceField(
        queryset=user_models.AppUser.objects.all(),
        widget=autocomplete.ModelSelect2(url='autocomplete:user_autocomplete')
    )

    team_members = forms.ModelMultipleChoiceField(
        required=False,
        queryset=user_models.AppUser.objects.all(),
        widget=autocomplete.ModelSelect2Multiple('autocomplete:user_autocomplete', forward=(
            'team_leader', forward.Self(), forward.Const({'limit': 4, 'only_supervisor': False}, 'args')))
    )

    graduation_date = forms.DateField(
        label='Przewidywana data obrony',
        widget=DatePickerInput(format='%d/%m/%Y')
    )

    technology = fields.TechnologyField(create_if_none=True, label='Technologie', multiple=True, max_length=500,
                                        widget=TaggingSelect2('autocomplete:technology_autocomplete'))

    class Meta:
        model = models.Group
        fields = ['title', 'graduation_date']


class GroupBySupervisorForm(forms.ModelForm):
    technology = fields.TechnologyField(create_if_none=True, label='Technologie', multiple=True, max_length=500,
                                        widget=TaggingSelect2('autocomplete:technology_autocomplete'))

    graduation_date = forms.DateField(
        label='Przewidywana data obrony',
        widget=DatePickerInput(format='%d/%m/%Y')
    )

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        instance = kwargs.get('instance')
        technologies = instance.technologies.all()
        initial['technology'] = technologies
        super(GroupBySupervisorForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.technologies.clear()
        return super().save(commit)

    class Meta:
        model = models.Group
        fields = ['title', 'graduation_date', 'git_repository', 'project_management_board', 'graduation_date']


class GroupByLeaderForm(forms.ModelForm):
    technology = fields.TechnologyField(create_if_none=True, label='Technologie', multiple=True, max_length=500,
                                        widget=TaggingSelect2('autocomplete:technology_autocomplete'))

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        instance = kwargs.get('instance')
        technologies = instance.technologies.all()
        initial['technology'] = technologies
        super(GroupByLeaderForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.technologies.clear()
        return super().save(commit)

    class Meta:
        model = models.Group
        fields = ['title', 'git_repository', 'project_management_board', 'informations']


class GroupAddMember(forms.Form):
    member = forms.ModelChoiceField(
        label='',
        queryset=user_models.AppUser.objects.all(),
        widget=autocomplete.ModelSelect2(url='autocomplete:user_autocomplete')
    )


class GroupSiteForm(forms.ModelForm):
    class Meta:
        model = models.GroupSite
        fields = ['content']
        widgets = {
            'content': TinyMCE(attrs={'cols': 80, 'rows': 30})
        }


class GroupAppUserForm(forms.ModelForm):
    class Meta:
        model = models.GroupAppUser
        fields = ['role']
        labels = {
            'role': ''
        }


class MembersForm(forms.Form):
    team_members = forms.ModelMultipleChoiceField(
        required=False,
        queryset=user_models.AppUser.objects.all(),
        widget=autocomplete.ModelSelect2(url='autocomplete:user_autocomplete')
    )


def get_groupappuser_formset():
    formset = forms.modelformset_factory(model=models.GroupAppUser, fields=('role',), labels={'role': ''}, extra=0)
    return formset

app/apps/group/views.py
from django import http
from django.contrib.auth import mixins
from django.shortcuts import render, redirect
from django.views import generic
from django_filters.views import FilterView

from utils.mixins import access_mixins
from . import models, forms, tables, filters
from ..index import views as base_views
from ..notifications import utils
from ..post import models as post_models


class GroupDetailView(base_views.UserWithRoleInGroupMixin, mixins.LoginRequiredMixin, access_mixins.UserInGroup,
                      generic.DetailView):
    model = models.Group
    context_object_name = 'group'

    def get(self, request, *args, **kwargs):
        utils.visit_group(self.request.user, self.get_object())
        return super().get(request, args, kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['members'] = models.GroupAppUser.objects.filter(group_id=self.kwargs.get('pk'))
        context['posts'] = post_models.Post.objects.filter(group_id=self.kwargs.get('pk')).order_by('-post_date')[:10]
        return context

    def can_use_config(self):
        user_role = self.object.get_user_role_in_group(user_id=self.request.user.id).role
        if user_role == models.RoleInGroup.SUPERVISOR or user_role == models.RoleInGroup.LEADER:
            return True


class GroupListView(mixins.LoginRequiredMixin, FilterView, base_views.BaseTableView):
    model = models.Group
    table_class = tables.AllGroupsTable
    filterset_class = filters.GroupFilter
    context_object_name = 'groups'
    paginate_by = 10
    template_name = "group/group_list.html"


class UserGroupsListView(GroupListView):
    table_class = tables.GroupTable

    def get_queryset(self):
        return self.request.user.diploma_groups.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups_to_accept'] = self.get_groups_to_accept()
        return context

    def get_groups_to_accept(self):
        app_user_groups = models.GroupAppUser.objects.filter(user_id=self.request.user.id, accepted=False).all()
        groups = [app_user_group.group for app_user_group in app_user_groups]
        return groups


class GroupCreateView(mixins.LoginRequiredMixin, generic.CreateView):
    model = models.Group
    form_class = forms.GroupForm

    def form_valid(self, form):
        result = super().form_valid(form)
        # SUPERVISOR
        supervisor_group = models.GroupAppUser(user=self.request.user, group=form.instance,
                                               role=models.RoleInGroup.SUPERVISOR)
        supervisor_group.save()

        # LEADER
        team_leader = form.cleaned_data['team_leader']
        team_leader_group = models.GroupAppUser(user=team_leader, group=form.instance,
                                                role=models.RoleInGroup.LEADER)
        team_leader_group.save()

        # MEMBERS
        for team_member in form.cleaned_data['team_members']:
            form.instance.members.add(team_member)

        # TECHNOLOGIES
        for technology in form.cleaned_data['technology']:
            form.instance.technologies.add(technology)

        return result


class GroupUpdateView(base_views.UserWithRoleInGroupMixin, mixins.LoginRequiredMixin, generic.UpdateView):
    model = models.Group

    def get_form_class(self):
        user_group_role = self.object.get_user_role_in_group(user_id=self.request.user.id)
        if user_group_role.role == models.RoleInGroup.SUPERVISOR:
            return forms.GroupBySupervisorForm
        elif user_group_role.role == models.RoleInGroup.LEADER:
            return forms.GroupByLeaderForm

    def form_valid(self, form):
        result = super().form_valid(form)

        for technology in form.cleaned_data.get('technology', []):
            form.instance.technologies.add(technology)

        return result


class GroupAcceptMembershipView(mixins.LoginRequiredMixin, generic.View):

    def get_group_user(self, group_id, user_id):
        return models.GroupAppUser.objects.filter(group_id=group_id, user_id=user_id).first()

    def get(self, request, pk):
        group_user = self.get_group_user(pk, self.request.user)
        if group_user:
            group_user.accepted = True
            group_user.save()
            return redirect(group_user.group)
        else:
            return http.HttpResponseNotFound()


class PrivateGroupSiteDetailView(base_views.UserWithRoleInGroupMixin, mixins.LoginRequiredMixin,
                                 access_mixins.UserInGroup, generic.DetailView):
    model = models.GroupSite
    context_object_name = 'site'

    def get_object(self, *args, **kwargs):
        return models.GroupSite.objects.filter(group_id=self.kwargs.get('pk'), is_public=False).first()


class PublicGroupSiteDetailView(base_views.UserWithRoleInGroupMixin, mixins.LoginRequiredMixin, generic.DetailView):
    model = models.GroupSite
    context_object_name = 'site'

    def get_object(self, *args, **kwargs):
        return models.GroupSite.objects.filter(group_id=self.kwargs.get('pk'), is_public=True).first()


class GroupSiteUpdateView(base_views.UserWithRoleInGroupMixin, mixins.LoginRequiredMixin, access_mixins.UserInGroup,
                          generic.UpdateView):
    model = models.GroupSite
    form_class = forms.GroupSiteForm

    def get_object(self, *args, **kwargs):
        if self.kwargs.get('is_public'):
            return models.GroupSite.objects.filter(group_id=self.kwargs.get('pk'), is_public=True).first()
        else:
            return models.GroupSite.objects.filter(group_id=self.kwargs.get('pk'), is_public=False).first()


class GroupMembersView(base_views.UserWithRoleInGroupMixin, mixins.LoginRequiredMixin, access_mixins.IsSupervisor,
                       generic.View):

    def get_group(self, pk):
        return models.Group.objects.filter(pk=pk).first()

    def get_add_user_form(self):
        return forms.GroupAddMember

    def get_context_data(self, group, **kwargs):
        context = super().get_context_data()
        context['add_user_form'] = self.get_add_user_form()
        context['group'] = group
        context['leader'] = group.get_leader()
        return context

    def get(self, request, pk):
        group = self.get_group(pk)
        if not group:
            return http.HttpResponseNotFound('Group not found')
        context = self.get_context_data(group)
        return render(request, 'group/group_members_form.html', context=context)

    def post(self, request, pk):
        group = self.get_group(pk)
        formset = forms.get_groupappuser_formset()
        group_members_formset = formset(request.POST)
        if group_members_formset.is_valid():
            group_members_formset.save()
            return redirect(group)
        else:
            return http.HttpResponseBadRequest(group_members_formset.errors)


class AddMemberToGroupView(base_views.UserWithRoleInGroupMixin, mixins.LoginRequiredMixin, access_mixins.IsSupervisor,
                           generic.View):
    def post(self, request, pk):
        form = forms.GroupAddMember(request.POST)
        if form.is_valid():
            member = form.cleaned_data['member']
            if not models.GroupAppUser.objects.filter(user=member, group_id=pk):
                member_group = models.GroupAppUser(user=member, group_id=pk,
                                                   role=models.RoleInGroup.STUDENT)
                member_group.save()
        return redirect('group:group-members', pk)


class GroupMembersManagementView(base_views.UserWithRoleInGroupMixin, mixins.LoginRequiredMixin,
                                 access_mixins.IsSupervisor, generic.View):

    def get(self, request, groupid, userid, action):
        group = models.Group.objects.filter(pk=groupid).first()
        member = models.GroupAppUser.objects.filter(group_id=groupid, user_id=userid).first()
        if action == 1:  # Promote leader
            leaderid = group.get_leader().id
            leader = models.GroupAppUser.objects.filter(group_id=groupid, user_id=leaderid).first()
            leader.role = models.RoleInGroup.STUDENT
            leader.save()
            member.role = models.RoleInGroup.LEADER
            member.save()
        elif action == 2:  # Delete User
            member.delete()
        return redirect('group:group-members', pk=groupid)


class GroupIntegrations(base_views.UserWithRoleInGroupMixin, mixins.LoginRequiredMixin,
                                 access_mixins.UserInGroup, generic.DetailView):
    model = models.Group
    context_object_name = 'group'
    template_name = 'group/group_integrations.html'

app/apps/group/templates/group/group_detail.html
{% extends 'base/base.html' %}
{% load post_tags %}
{% load group_attachments %}
{% load group_meets %}

{% block content %}
    <div class="pagetitle">
        <h1>{{ group.title }}</h1>
    </div>
    <div class="row align-items-top">


        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Informacje</h5>
                    <div class="row col-12">
                        {% if group.git_repository %}
                            <div class="col-md-2 label">Git</div>
                            <div class="col-md-10 text-break"><a href="{{ group.git_repository }}"
                                                              target="_blank">{{ group.git_repository }}</a></div>
                        {% endif %}
                        {% if group.project_management_board %}
                            <div class="col-md-2 label">Tablica</div>
                            <div class="col-md-10 text-break"><a href="{{ group.project_management_board }}"
                                                              target="_blank">{{ group.project_management_board }}</a>
                            </div>
                        {% endif %}
                        {% if group.informations %}
                            <div class="col-md-2 label">Opis</div>
                            <div class="col-md-10 text-break">
                                <p style="white-space: pre">{{ group.informations }}</p>
                            </div>
                        {% endif %}
                        {% if group.technologies.all %}
                            <div class="col-md-2 label">Technologie</div>
                            <div class="col-md-10 text-break">
                                {% for technology in group.technologies.all %}
                                    <span class="badge rounded-pill bg-primary">{{ technology.name }}</span>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Posty</h5>
                    {% post_form group.id user %}
                    <div class="list-group">
                        {% for post in posts %}
                            {% render_post post %}
                            {% empty %}
                            <h3>Brak postów</h3>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            {% render_group_meets group user %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Członkowie</h5>
                    <ul>
                        {% for member in members %}
                            <li>
                                {{ member.user }} - {{ member.get_role_display }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% render_attachments group %}
        </div>

    </div>
{% endblock content %}

app/apps/group/templates/group/group_form.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    {% if object %}
                        Edytuj Grupę
                    {% else %}
                        Stwórz grupę
                    {% endif %}
                </h5>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-group pt-2 d-flex justify-content-end">
                        <button class="btn btn-success" type="submit">Zapisz</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block footer %}

    {{ form.media }}

{% endblock footer %}

app/apps/group/templates/group/group_integrations.html
{% extends 'base/base.html' %}
{% load post_tags %}
{% load group_attachments %}
{% load group_meets %}

{% block content %}
    <div class="pagetitle">
        <h1>Integracje</h1>
    </div>
    <div class="row align-items-top">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Bitbucket</h5>
                    <div class="row col-12">
                        <p>
                            Aby dodać integracje, należy wejść na Bitbucket, repozytorium,<br>
                            Następnie w <strong>Repository settings/Webhooks/Add Webhook</strong><br>
                            W triggers zaznaczamy <strong>Repository/Push</strong> (wszystkie inne odznaczamy)<br>
                            URL dla twojej grupy to: <strong>{{ request.get_host }}/git/bitbucket/{{ group.uuid }}</strong>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock content %}

app/apps/group/templates/group/group_list.html
{% extends 'base/base.html' %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}

{% block content %}
    {% if not user.is_supervisor %}
        {% if groups_to_accept %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Grupy do akceptacji</h5>
                    <div>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>
                                    Tytuł
                                </th>
                                <th>
                                    Promotor
                                </th>
                                <th>
                                    Akcje
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for group_to_accept in groups_to_accept %}
                                <tr>
                                    <td>
                                        {{ group_to_accept.title }}
                                    </td>
                                    <td>
                                        {{ group_to_accept.get_supervisor }}
                                    </td>
                                    <td>
                                        <a class="btn btn-success"
                                           href="{% url 'group:group-accept-membership' group_to_accept.id %}"
                                           role="button">Akceptuj</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endif %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Grupy</h5>
            {% if groups %}
                <form action="" method="get" class="form row mb-3">
                    {% for field in filter.form %}
                        <div class="col-md-3">
                            <div class="form-label">
                                {{ field.label_tag }}
                            </div>
                            <div class="form-field">
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                    {#                        {{ filter.form }}#}
                    <div class="col-md-3 d-flex align-items-end justify-content-start pt-2">
                        <input type="submit" class="btn btn-primary px-5" value="Filtruj"/>
                    </div>
                </form>
                {#                {% endif %}#}
                {% render_table table %}
                {% else %}
                <h2>Nie posiadasz grupy stwórz nową {% if user.is_supervisor %}<a class="btn btn-success" href="{% url 'group:group-create' %}">Stwórz grupę</a>{% endif %}</h2>
            {% endif %}
        </div>
    </div>
{% endblock content %}

{% block footer %}

    {{ filter.form.media }}

{% endblock footer %}

app/apps/group/templates/group/group_members_form.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    Członkowie grupy
                </h5>
                <div>
                    {% for member in group.get_members %}
                        <div class="row col-lg-6 col-md-12 mb-1">
                            <div class="col-4 d-flex align-items-center">
                                {{ member }}
                            </div>
                            <div class="row col-8">
                                {% if member != leader %}
                                    <div class="col-6">
                                        <a class="btn btn-success"
                                           href="{% url 'group:group-management' groupid=group.id userid=member.id action=1 %}">
                                            Lider
                                        </a>
                                    </div>
                                    <div class="col-6">
                                        <a class="btn btn-danger"
                                           href="{% url 'group:group-management' groupid=group.id userid=member.id action=2 %}">
                                            Usuń
                                        </a>
                                    </div>
                                {% else %}
                                    <div class="col-6">
                                        <a class="btn btn-success disabled">
                                            Lider
                                        </a>
                                    </div>
                                    <div class="col-6">
                                        <a class="btn btn-danger disabled">
                                            Usuń
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                            <br/>
                        </div>
                    {% endfor %}
                </div>
                <hr />
                <h4 class="card-title pt-0">
                    Dodaj Studenta
                </h4>
                <form class="form form-inline row my-2" method="post"
                      action="{% url 'group:add-group-user' group.id %}">
                    {% csrf_token %}
                    <div class="col-6">
                        {{ add_user_form|crispy }}
                    </div>
                    <div class="col-6">
                        <button class="btn btn-primary" type="submit">Zapisz</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block footer %}
    {{ add_user_form.media }}
{% endblock %}

app/apps/group/templates/group/groupsite_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title d-flex w-100 justify-content-between">
                {% if site.is_public %}
                    Strona Publiczna
                    {% if role %}
                        <a class="btn btn-success" href="{% url 'group:group-site-update' site.group_id 1 %}">Edytuj
                            Stronę</a>
                    {% endif %}
                {% else %}
                    Strona Prywatna
                    {% if role %}
                        <a class="btn btn-success" href="{% url 'group:group-site-update' site.group_id 0 %}">Edytuj
                            Stronę</a>
                    {% endif %}
                {% endif %}
            </h5>
            {% if site.content %}
                <div class="text-break">
                    {{ site.content|safe }}
                </div>
                {% else %}
                    <h3>Brak informacji o grupie</h3>
            {% endif %}
        </div>
    </div>
{% endblock content %}

app/apps/group/templates/group/groupsite_form.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">
                Edytuj Stronę
            </h5>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="form-group pt-2 d-flex justify-content-end">
                    <button class="btn btn-success" type="submit">Zapisz</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    {{ form.media }}
{% endblock footer %}