app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('apps.index.urls')),
                  path('account/', include('apps.account.urls')),
                  path('group/', include('apps.group.urls')),
                  path('post/', include('apps.post.urls')),
                  path('technology/', include('apps.technology.urls')),
                  path('announcements/', include('apps.announcements.urls')),
                  path('user/', include('apps.user.urls')),
                  path('autocomplete/', include('apps.autocomplete.urls')),
                  path('attachment/', include('apps.attachment.urls')),
                  path('admin/', admin.site.urls),
                  path('tinymce/', include('tinymce.urls')),
                  path('meet/', include('apps.meets_calendar.urls')),
                  path('git/', include('apps.git_service.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

app/apps/post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [
    path('<int:pk>/new/', views.CreatePostView.as_view(), name='create-post')
]

app/apps/post/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone

from apps.account import models as account_models
from apps.group import models as group_models
from apps.notifications import utils


class Post(models.Model):
    author = models.ForeignKey(account_models.AppUser, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Autor', help_text='Autor')
    group = models.ForeignKey(group_models.Group, on_delete=models.CASCADE, verbose_name='Grupa', help_text='Grupa')

    content = models.TextField(max_length=500, verbose_name='Treść', help_text='Treść')
    post_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Data', help_text='Data')

    integration = models.TextField(max_length=50, blank=True, choices=settings.INTEGRATIONS_CHOICES)

    def get_absolute_url(self):
        return reverse('group:group-detail', args=[self.group_id])

    def save(self, *args, **kwargs):
        if not self.pk:
            super().save(*args, **kwargs)
            self.group.last_post = timezone.now()
            self.group.save()
        else:
            super().save(*args, **kwargs)
        if self.integration:
            utils.add_notification('integracja', self.group, f'Nowy commit w grupie {self.group.title}')
        else:
            utils.add_notification(self.author, self.group, f'Nowy post w grupie {self.group.title}')

    def __str__(self):
        return f'id:{self.id}, grupa:{self.group.id}, autor:{self.author}'

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posty'

app/apps/post/forms.py
from django import forms

from . import models


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['content']
        labels = {'content': ''}
        help_texts = {'content': ''}
        widgets = {'content': forms.Textarea(attrs={'rows': 2, 'cols':50})}

app/apps/post/views.py
from django.contrib.auth import mixins
from django.views import generic

from utils.mixins import access_mixins
from . import models, forms


class CreatePostView(mixins.LoginRequiredMixin, access_mixins.UserInGroup, generic.CreateView):
    model = models.Post
    form_class = forms.CreatePostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.group_id = self.kwargs.get('pk')
        return super(CreatePostView, self).form_valid(form)

app/apps/post/templates/post/post_detail.html
<div class="list-group-item list-group-item-action">
    <div class="d-flex align-items-start">
        <div class="d-flex flex-row align-items-center">
            {% if integration %}
            <img class="rounded-circle mini-photo" src="{{ integration.avatar }}" alt="avatar">
            {% else %}
            <img class="rounded-circle mini-photo" src="{{ post.author.get_avatar_url }}" alt="avatar">
            {% endif %}
        </div>
        <div class="px-2 w-100">
            <div class="d-flex justify-content-between">
                {% if integration %}
                <h5 class="mb-1">{{ integration.username }}</h5>
                {% else %}
                <h5 class="mb-1">{{ post.author }}</h5>
                {% endif %}
                <small>{{ post.post_date|date:'Y-m-d H:i' }}</small>
            </div>
            <p class="text-break">{{ post.content|safe }}</p>
        </div>
    </div>
</div>

app/apps/post/templates/post/post_form.html
{% load crispy_forms_tags %}
<div class="align-items-center w-100 py-2">
    <form method="post" action="{% url 'post:create-post' pk=group_id %}">
        {% csrf_token %}
        <div class="w-100 px-2 align-items-center">
            <div class="d-flex flex-row w-100">
                <img class=" img-responsive rounded-circle" src="{{ user.get_avatar_url }}" width="50" height="50">
                <div class="w-100 px-2 d-flex align-items-center">
                    <div class="w-100">
                        {{ form|crispy }}
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Dodaj</button>
            </div>
        </div>
    </form>
</div>