app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('apps.index.urls')),
                  path('account/', include('apps.account.urls')),
                  path('group/', include('apps.group.urls')),
                  path('post/', include('apps.post.urls')),
                  path('technology/', include('apps.technology.urls')),
                  path('announcements/', include('apps.announcements.urls')),
                  path('user/', include('apps.user.urls')),
                  path('autocomplete/', include('apps.autocomplete.urls')),
                  path('attachment/', include('apps.attachment.urls')),
                  path('admin/', admin.site.urls),
                  path('tinymce/', include('tinymce.urls')),
                  path('meet/', include('apps.meets_calendar.urls')),
                  path('git/', include('apps.git_service.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

app/apps/group/urls.py
from django.urls import path

from . import views

app_name = 'group'
urlpatterns = [
    path('', views.GroupListView.as_view(), {'title': 'testTitle'}, name='group-list'),
    path('my-groups/', views.UserGroupsListView.as_view(), {'title': 'testTitle'}, name='user-group-list'),
    path('<int:pk>', views.GroupDetailView.as_view(), name='group-detail'),
    path('new/', views.GroupCreateView.as_view(), name='group-create'),
    path('<int:pk>/update', views.GroupUpdateView.as_view(), name='group-update'),
    path('<int:pk>/site/private/', views.PrivateGroupSiteDetailView.as_view(), name='private-group-site-detail'),
    path('<int:pk>/site/public/', views.PublicGroupSiteDetailView.as_view(), name='public-group-site-detail'),
    path('<int:pk>/site/update/<int:is_public>', views.GroupSiteUpdateView.as_view(), name='group-site-update'),
    path('<int:pk>/members', views.GroupMembersView.as_view(), name='group-members'),
    path('<int:pk>/accept', views.GroupAcceptMembershipView.as_view(), name='group-accept-membership'),
    path('<int:groupid>/members/update/<int:userid>/<int:action>', views.GroupMembersManagementView.as_view(), name='group-management'),
    path('<int:pk>/members/add', views.AddMemberToGroupView.as_view(), name='add-group-user'),
    path('<int:pk>/integrations', views.GroupIntegrations.as_view(), name='group-integrations')
]

app/apps/technology/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from . import views

app_name = 'technology'
urlpatterns = [
    path('<int:pk>/', views.TechnologyDetailView.as_view(), name='technology-detail'),
    path('search/', views.TechnologySearchView.as_view(), name='technology-search'),
    path('new/', views.TechnologyCreateView.as_view(), name='technology-create'),
]

app/apps/technology/models.py
from django.db import models
from django.urls import reverse

from apps.account import models as account_models


class Technology(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nazwa', help_text='Nazwa technologii')
    user = models.ForeignKey(account_models.AppUser, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Dodał', help_text='Dodał', editable=False)

    def get_absolute_url(self):
        return reverse('technology:technology-detail', args=[self.id])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Technologia'
        verbose_name_plural = 'Technologie'

app/apps/technology/views.py
from django.views import generic

from . import models


class TechnologyDetailView(generic.DetailView):
    model = models.Technology
    context_object_name = 'technology'


class TechnologySearchView(generic.ListView):
    model = models.Technology
    context_object_name = 'technologies'

    def get_queryset(self):
        technology_name = self.request.GET.get('technology_name')
        if technology_name:
            return models.Technology.objects.filter(name=technology_name)
        else:
            return super().get_queryset()


class TechnologyCreateView(generic.CreateView):
    model = models.Technology
    fields = ['name']

app/apps/technology/templates/technology/technology_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="content">
        <p>id: {{ technology.id }}</p>
        <p>name: {{ technology.name }}</p>
        <div>
            <h3>Grupy:</h3>
            <ul>
                {% for group in technology.GroupTechnology.all %}
                    <li>
                        <a href="{% url 'group:public-group-site-detail' pk=group.id %}">
                            {{ group.title }}
                        </a>
                    </li>
                {% empty %}
                    <h3>Brak grup</h3>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

app/apps/technology/templates/technology/technology_form.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom">Dodaj Technologię</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">Zapisz</button>
            </div>
        </form>
    </div>
{% endblock content %}

app/apps/technology/templates/technology/technology_list.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="content col-12">
        <div class="col-12">
            <h2>Technologie</h2>
            <a class="btn btn-success" href="{% url 'technology:technology-create' %}">Dodaj technologię</a>
            <hr class="col-12">
            {% for technology in technologies %}
                <a href="{% url 'technology:technology-detail' technology.id %}"><p>{{ technology.name }}</p></a>
            {% empty %}
                <h3>Nie ma projektów z taką technologią</h3>
            {% endfor %}
        </div>
    </div>
{% endblock content %}